### ISSUE TITLE
Crash when use YYLabel with empty string

### ISSUE THREAD

**Issue by gssdromen** [lalawue/PinStackView#1]
<img width="1973" alt="image" src="https://github.com/lalawue/PinStackView/assets/2989634/11cf74ed-044b-4574-bdf4-249d2837e1de">

```
import UIKit
import PinStackView
import YYText

class TestView: UIView {
  let titleLabel: YYLabel = {
    let label = YYLabel()
    return label
  }()

  let icon: UIImageView = {
    let v = UIImageView()
    return v
  }()

  let stackView: PinStackView = {
    let s = PinStackView()
    s.style = .auto
    s.spacing = 4
    s.alignment = .center
    return s
  }()

  override init(frame: CGRect) {
    super.init(frame: frame)
    stackView.addItem(icon).size(16, 16)
    stackView.addItem(titleLabel).top(0).bottom(0).shrink(1)
    addSubview(stackView)
  }
  
  required init?(coder: NSCoder) {
    fatalError("init(coder:) has not been implemented")
  }

  override func layoutSubviews() {
    super.layoutSubviews()
    stackView.pin
      .top(0).left(8).right(8)
      .height(20)
    stackView.markDirty()
  }
}

```

add this view to an empty vc, it will crash at launch

**Comment by gssdromen** [comment]
It looks like alloc a PinLayout here and lose the left info?
<img width="1709" alt="image" src="https://github.com/lalawue/PinStackView/assets/2989634/317b69f3-0e03-48f0-bfb5-4961c99f3fbb">

**Comment by lalawue** [comment]
> It looks like alloc a PinLayout here and lose the left info? <img alt="image" width="1709" src="https://private-user-images.githubusercontent.com/2989634/285086741-317b69f3-0e03-48f0-bfb5-4961c99f3fbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5NzMyMjEsIm5iZiI6MTcwMDk3MjkyMSwicGF0aCI6Ii8yOTg5NjM0LzI4NTA4Njc0MS0zMTdiNjlmMy0wZTAzLTQ4ZjAtYmZiNS00OTYxYzk5ZjNmYmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjZUMDQyODQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTE2YTRmNzg4YWUxYmZkNjE2MGQxZWJhY2Q4OTRiMDYwNjUyZTFmZWQzZWVmMmNhZjcyN2RhY2ZjYTlkMDQ3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.77MHNlVBcES_K-Mvgh93YhUf5sc5MbBtngBApRfkMZU">

works fine in my case, with 'empty' text label:

![Simulator Screen Shot - iPhone 14 Pro - 2023-11-26 at 12 30 21](https://github.com/lalawue/PinStackView/assets/1954838/21977371-7941-485e-98eb-6b24b0647e9c)

```swift
import UIKit
import PinStackView

extension UIView {
    func setupBorder(width: CGFloat = 0.5, color: UIColor? = nil) {
        layer.borderWidth = width
        layer.borderColor = color?.cgColor ?? UIColor.black.cgColor
        layer.masksToBounds = true
    }
}

class TestView: PinStackView {
    
    let iconView = UIImageView().then {
        $0.setupBorder()
    }
    
    let titleLabel = UILabel().then {
        $0.setupBorder()
    }
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        setupBorder(width: 0.5)
        spacing = 4
        alignment = .center
        padding = UIEdgeInsets(top: 5, left: 8, bottom: 5, right: 8)
        addItem(iconView).size(20)
        addItem(titleLabel).grow(1)
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}

class TestViewDemoController: UIViewController {
    
    let testView = TestView()

    override func viewDidLoad() {
        super.viewDidLoad()
        view.addSubview(testView)
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        testView.pin.top(200).horizontally().height(30)
    }
}

```

**Comment by gssdromen** [comment]
@lalawue Can you try use YYLabel and PinStackView auto style

**Comment by lalawue** [comment]
> @lalawue Can you try use YYLabel and PinStackView auto style

I will look into it

**Comment by lalawue** [comment]
> @lalawue Can you try use YYLabel and PinStackView auto style

You can try the latest commit: https://github.com/lalawue/PinStackView/commit/f46357bcb390f8a5b72ca83677666721ff4026f8
